---
- name: Play 1 - Install misl softwares and Apache
  hosts: webserver
  become: yes
  roles:
    - misl
    - apache

- name: Play 2 - configure Apache
  hosts: webserver
  become: yes
  tasks:
    - name: copy the bulletclub code
      copy:
        src: /etc/ansible/bulletclub/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root

    - name: copy the proxypass file
      copy:
        src: /etc/ansible/bulletclub/proxypass.conf
        dest: /etc/httpd/conf.d/proxypass.conf
        owner: root
        group: root

    - name: selinux
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
      tags: selinux

    - name: Reload service httpd, in all cases
      service:
        name: httpd
        state: reloaded

